- name: apply manifest
  block:
  - include_role: {name: utils, tasks_from: dl_to_temp_file}
    vars: {url: "{{lh_manifest_url}}"}

- name: apply manifest
  become: true
  kubernetes.core.k8s:
    state: present
    src: "{{tempfile.path}}"
    wait: true