---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data
  namespace: docker-registry
  labels:
    app: docker-registry
spec:
  resources:
    requests: 
      storage: 5Gi
  accessModes:
  - ReadWriteMany
  storageClassName: longhorn
---
apiVersion: v1
kind: Deployment
metadata:
  name: registry
  namespace: docker-registry
  labels:
    app: docker-registry
spec:
  selector:
    matchLabels:
      app: docker-registry
  replicas: 1
  template:
    name: registry
    namespace: docker-registry
    metadata:
      labels:
        app: docker-registry
    spec:
      containers:
      - name: registry
        image: registry:2.6.2
        volumeMounts:
        - name: data
          mountPath: "/var/lib/registry"
        - name: certs
          mountPath: "/certs"
          readOnly: true
        env:
        - name: REGISTRY_HTTP_TLS_CERTIFICATE
          value: /certs/tls.crt
        - name: REGISTRY_HTTP_TLS_KEY
          value: /certs/tls.key
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: data
      - name: certs
        secret:
          secretName: certs
---
apiVersion: v1
kind: Service
metadata:
  name: registry
  namespace: docker-registry
  labels:
    app: docker-registry
  annotations:
    "metallb-mdns/hostname": "{{dr_hostname}}"
spec:
  selector:
    app: docker-registry
  ports:
  - port: 443
    targetPort: 5000
  type: LoadBalancer