---
apiVersion: v1
kind: Secret
metadata:
  name: certs
  namespace: docker-registry
  labels:
    app: docker-registry
data:
  "tls.crt": "{{dr_certificate}}"
  "tls.key": "{{dr_key}}"
  "ca.crt": "{{dr_ca_certificate}}"
  "ca.key": "{{dr_ca_key}}"