- hosts: all
  gather_facts: true
  tasks: []
    
- hosts: all
  gather_facts: false
  roles:
    - disable_swap
    - enable_bridged_networking
    - enable_overlayfs
    - enable_cgroups
    - install_kubectl
    - install_k3s
    - install_pip
    - install_openshift_python_client
    - install_cni_plugins

- hosts: kubernetes_primary
  gather_facts: false
  roles:
    - set_up_k3s_server

- hosts: kubernetes_secondary
  gather_facts: false
  roles:
    - set_up_k3s_agent

- hosts: kubernetes_primary
  gather_facts: false
  roles:
    - install_cni

