- hosts: all
  gather_facts: true
  roles: []

- hosts: kubernetes_primary
  gather_facts: false
  roles:
    - install_cni 
  vars:
    role_action: "uninstall"

- hosts: kubernetes_secondary
  gather_facts: false
  roles:
    - set_up_k3s_agent
  vars:
    role_action: "uninstall"

- hosts: kubernetes_primary
  gather_facts: false
  roles:
    - set_up_k3s_server 
  vars:
    role_action: "uninstall"

- hosts: all
  gather_facts: false
  roles:
    - install_cni_plugins
    - install_openshift_python_client
    - install_pip
    - install_k3s
    - install_kubectl
    - enable_cgroups
    - enable_overlayfs
    - enable_bridged_networking
    - disable_swap
  vars:
    role_action: "uninstall"




