- name: flush current iptables
  become: true
  retries: 3
  delay: 1
  ansible.builtin.command:
    cmd: iptables -F
  changed_when: false

- name: set iptables alternative
  become: true
  community.general.alternatives:
    name: iptables
    path: /usr/sbin/iptables-legacy
  notify: [li | reboot]

- name: set ip6tables alternative
  become: true
  community.general.alternatives:
    name: ip6tables
    path: /usr/sbin/ip6tables-legacy
  notify: [li | reboot]