- name: "Running k3s-install.sh"
  become: true
  command:
    cmd: "k3s-install.sh"
  environment:
    INSTALL_K3S_VERSION: "{{ k3s_version }}"
    INSTALL_K3S_EXEC: "server --disable=servicelb --disable=traefik --disable=local-storage --disable=metrics-server --flannel-backend=none"
    INSTALL_K3S_SYMLINK: "skip"

- name: "Get user information"
  check_mode: true
  user:
    name: "{{ ansible_user_id }}"
  register: user

- name: "({{ user.name }}) Creating .kube folder"
  file:
    path: "{{ user.home }}/.kube"
    state: directory

- name: "({{ user.name }}) Copying kubeconfig"
  become: true
  copy:
    src: "/etc/rancher/k3s/k3s.yaml"
    dest: "{{ user.home }}/.kube/config"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    remote_src: true

- name: "Reboot"
  become: true
  reboot:
