- name: "Check if uninstall script exists"
  shell:
    cmd: command -v k3s-uninstall.sh
  failed_when: false
  register: uninstall_script_exists

- name: "Check if uninstall script exists"
  set_fact:
    uninstall_script_exists: "{{ uninstall_script_exists.rc == 0 }}"

- block:
  - name: "Running k3s-uninstall.sh"
    become: true
    command:
      cmd: "k3s-uninstall.sh"

  - name: "Reboot"
    become: True
    reboot:
  when: "uninstall_script_exists == True"

- name: "Get user information"
  check_mode: true
  user:
    name: "{{ ansible_user_id }}"
  register: user

- name: "({{ user.name }}) Deleting .kube folder"
  file:
    path: "{{ user.home }}/.kube"
    state: absent
