# generate CA
- name: generate temp certificate authority key file
  ansible.builtin.tempfile:
    state: file
  register: temp_ca_key_file
  changed_when: false

- name: generate temp certificate authority request file 
  ansible.builtin.tempfile:
    state: file
  register: temp_ca_request_file

- name: generate temp certificate authority file
  ansible.builtin.tempfile:
    state: file
  register: temp_ca_file
  changed_when: false

- name: generate certificate authority key
  ansible.builtin.openssl_privatekey:
    path: "{{temp_ca_key_file.path}}"
    size: 2048
  changed_when: false

- name: generate certificate authority request
  community.crypto.openssl_csr:
    path: "{{temp_ca_request_file.path}}"
    privatekey_path: "{{temp_ca_key_file.path}}"

- name: generate certificate authority
  ansible.builtin.openssl_certificate:
    path: "{{temp_ca_file.path}}"
    privatekey_path: "{{temp_ca_key_file.path}}"
    csr_path: "{{temp_ca_request_file.path}}"
    provider: selfsigned
  changed_when: false

- name: read temp certificate authority file
  ansible.builtin.slurp:
    src: "{{temp_ca_file.path}}"
  register: ca_file_cmd
  changed_when: false

- name: read temp certificate authority key file
  ansible.builtin.slurp:
    src: "{{temp_ca_key_file.path}}"
  register: ca_key_file_cmd
  changed_when: false

# generate certificate
- name: generate temp certificate key file 
  ansible.builtin.tempfile:
    state: file
  register: temp_certificate_key_file
  changed_when: false

- name: generate temp certificate request file 
  ansible.builtin.tempfile:
    state: file
  register: temp_certificate_request_file

- name: generate temp certificate file
  ansible.builtin.tempfile:
    state: file
  register: temp_certificate_file
  changed_when: false

- name: generate certificate key
  ansible.builtin.openssl_privatekey:
    path: "{{temp_certificate_key_file.path}}"
    size: 2048
  changed_when: false

- name: generate certificate request
  community.crypto.openssl_csr:
    path: "{{temp_certificate_request_file.path}}"
    privatekey_path: "{{temp_certificate_key_file.path}}"
    common_name: "{{common_name | default(omit)}}"
    subject_alt_name: "{{subject_alt_name | default(omit)}}"

- name: generate certificate
  ansible.builtin.openssl_certificate:
    path: "{{temp_certificate_file.path}}"
    privatekey_path: "{{temp_certificate_key_file.path}}"
    csr_path: "{{temp_certificate_request_file.path}}"
    ownca_path: "{{temp_ca_file.path}}"
    ownca_privatekey_path: "{{temp_ca_key_file.path}}"
    provider: ownca
  changed_when: false

- name: read temp certificate file
  ansible.builtin.slurp:
    src: "{{temp_certificate_file.path}}"
  register: certificate_file_cmd
  changed_when: false

- name: read temp certificate key file
  ansible.builtin.slurp:
    src: "{{temp_certificate_key_file.path}}"
  register: certificate_key_file_cmd
  changed_when: false

- name: set facts
  ansible.builtin.set_fact:
    certificate_authority: "{{ca_file_cmd.content}}"
    certificate_authority_key: "{{ca_key_file_cmd.content}}"
    certificate_key: "{{certificate_key_file_cmd.content}}"
    certificate: "{{certificate_file_cmd.content}}"
  changed_when: false
