- name: apply namespace manifest
  block:
  - include_role: {name: utils, tasks_from: dl_to_temp_file}
    vars: {url: "{{mlb_namespace_manifest_url}}"}

- name: apply namespace manifest
  become: true
  kubernetes.core.k8s:
    state: present
    src: "{{tempfile.path}}"
    wait: true

- name: check if secret generated
  become: true
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Secret
    name: memberlist
    namespace: metallb-system
  register: mlb_secret_search

- name: generate secret
  block:
  - name: generate secret key
    ansible.builtin.command:
      cmd: openssl rand -base64 128
    register: mlb_openssl_cmd

  - name: deploy secret
    become: true
    kubernetes.core.k8s:
      state: present
      definition: "{{lookup('template', 'templates/secret.yaml')}}"
      wait: true
    vars:
      mlb_secret_key: "{{mlb_openssl_cmd.stdout}}"
  when: not mlb_secret_search.resources

- name: deploy configmap
  become: true
  kubernetes.core.k8s:
    state: present
    definition: "{{lookup('template', 'templates/configmap.yaml')}}"
    wait: true

- name: apply manifest
  block:
  - include_role: {name: utils, tasks_from: dl_to_temp_file}
    vars: {url: "{{mlb_manifest_url}}"}
    
  - name: apply manifest
    become: true
    kubernetes.core.k8s:
      state: present
      src: "{{tempfile.path}}"
      wait: true
