- name: "Check if uninstall script exists"
  shell:
    cmd: command -v k3s-agent-uninstall.sh
  failed_when: false
  register: uninstall_script_exists

- name: "Check if uninstall script exists"
  set_fact:
    uninstall_script_exists: "{{ uninstall_script_exists.rc == 0 }}"

- block:
  - name: "Running k3s-agent-uninstall.sh"
    become: true
    command:
      cmd: "k3s-agent-uninstall.sh"

  - name: "Reboot"
    become: true
    reboot:
  when: "uninstall_script_exists == True"
