- name: create user
  become: true
  ansible.builtin.user:
    name: "{{username}}"
    password: "{{password | password_hash('sha512')}}"
    state: present
    shell: /bin/bash
    create_home: true
    append: true
    groups: [adm, sudo, netdev]

- name: enable passwordless sudo
  become: true
  ansible.builtin.copy:
    content: "{{lookup('template', 'templates/sudoers.j2')}}"
    remote_src: true
    dest: /etc/sudoers.d/99_{{username}}-nopasswd
    validate: visudo -cf %s
