- name: set server node hostname
  ansible.builtin.set_fact:
    k3s_server_hostname: "{{server_hostname}}"
  vars:
    server_hostname: "{{groups['k3s_server'][0]}}"

- name: set server node ip address
  ansible.builtin.set_fact:
    k3s_server_ip_address: "{{hostvars[k3s_server_hostname]['ansible_default_ipv4']['address']}}"

- name: get server node token
  become: true
  delegate_to: "{{k3s_server_ip_address}}"
  ansible.builtin.slurp:
    path: /var/lib/rancher/k3s/server/node-token
  register: server_token

- name: set server node token
  ansible.builtin.set_fact:
    k3s_server_node_token: "{{server_token.content | b64decode}}"

- name: run k3s.sh
  block:
  - include_role: {name: utils, tasks_from: dl_to_temp_file}
    vars: {url: "{{k3s_sh_url}}"}

  - name: run k3s.sh script
    ansible.builtin.command:
      cmd: "{{tempfile.path}} --docker"
    environment:
        K3S_URL: https://{{k3s_server_ip_address}}:6443
        K3S_TOKEN: "{{k3s_server_node_token}}"
    register:  k3s_sh
    changed_when: "'No change detected' not in k3s_sh.stdout"
    notify: [k3s | restart k3s-agent service]