- name: run k3s.sh script
  block:
  - include_role: {name: utils, tasks_from: dl_to_temp_file}
    vars: {url: "{{k3s_sh_url}}"}

  - name: run k3s.sh script
    ansible.builtin.command:
      cmd: "{{tempfile.path}} --docker"
    environment:
      INSTALL_K3S_EXEC: "--disable traefik --disable servicelb"
    register:  k3s_sh
    changed_when: "'No change detected' not in k3s_sh.stdout"
    notify: [k3s | restart k3 service]

- name: get root user
  check_mode: true
  become: true
  user:
    name: root
    state: present
  register: root_user

- name: create .kube directory
  become: true
  file:
    state: directory
    path: "{{root_user.home}}/.kube"

- name: symlink kubeconfig 
  become: true
  file:
    state: link
    path: "{{root_user.home}}/.kube/config"
    src: /etc/rancher/k3s/k3s.yaml

- name: create portable kubeconfig
  block:
  - name: get user
    check_mode: true
    become: true
    user:
      name: "{{ansible_user_id}}"
      state: present
    register: user
  
  - name: generate portable kubeconfig
    become: true
    k3s_config:
      user: admin
      hostname: "{{ansible_default_ipv4['address']}}"
      cluster: "{{inventory_hostname | replace('.local', '')}}"
    register: portable_kubeconfig
    changed_when: false

  - name: create ~/.kube directory
    file:
      state: directory
      path: "{{user.home}}/.kube"

  - name: write kubeconfig to file
    copy:
      content: "{{portable_kubeconfig.result | to_nice_yaml(sort_keys=True)}}"
      remote_src: true
      dest: "{{user.home}}/.kube/config"
