- name: install python3 (apt)
  become: true
  ansible.builtin.apt:
    pkg: [python3-dev, python3-pip]
    update_cache: true
    state: present

- name: install open-iscsi (apt)
  become: true
  ansible.builtin.apt:
    pkg: [open-iscsi]
    state: present

- name: install nfs (apt)
  become: true
  ansible.builtin.apt:
    pkg: [nfs-common]
    state: present

- name: install git (apt)
  become: true
  ansible.builtin.apt:
    pkg: [git]
    state: present

- name: install avahi-daemon (apt)
  become: true
  ansible.builtin.apt:
    pkg: [avahi-daemon]
    state: present

- name: install docker
  block:
  - name: add docker gpg key
    become: true
    ansible.builtin.apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: add docker repository
    become: true
    ansible.builtin.apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable
      state: present

  - name: install docker (apt)
    become: true
    ansible.builtin.apt:
      pkg: [docker-ce, docker-ce-cli, containerd.io]
      update_cache: true
      state: present
  
  - name: install docker (python)
    become: true
    ansible.builtin.pip:
      name: docker
  
  - name: add user to docker group
    become: true
    user:
      name: "{{ansible_user_id}}"
      groups: docker
      append: true

- name: install pyyaml (python)
  become: true
  ansible.builtin.pip:
    name: pyyaml

- name: install kubernetes (python)
  become: true
  ansible.builtin.pip:
    name: kubernetes
