- name: Enable swap
  become: true
  command: 
    cmd: "{{ item }}"
  with_items:
    - update-rc.d dphys-swapfile defaults
    - dphys-swapfile setup
    - dphys-swapfile swapon

- name: Enable swap service
  become: true
  systemd:
    name: dphys-swapfile
    state: started
    enabled: true

- name: "Uncomment swap entries in /etc/fstab"
  become: true
  replace:
    path: /etc/fstab
    regexp: '^#(\s*[^#\n]+\s+\w+\s+swap\s+.*)$'
    replace: '\1'
    backup: yes

- name: "Enable swap"
  become: true
  command:
    cmd: "swapon -a"
