- name: "Remove module-load.d conf file"
  become: true
  file:
    path: "{{ moduleloadd_path }}"
    state: absent

- name: "Get module list"
  set_fact:
    modules: "{{ lookup('file', 'files/module-load.d.conf') }}"

- name: "Unload modules"
  become: true
  command:
    cmd: "modprobe -r {{ item }}"
  with_items: "{{ modules.splitlines() }}"

- name: "Remove sysctl.d conf file"
  become: true
  file:
    path: "{{ sysctld_path }}"
    state: absent

- name: "Reload sysctl"
  become: true
  command:
    cmd: "sysctl --system"
