- hosts: all
  vars_prompt:
  - name: username
    prompt: Enter username
    private: false
  - name: password
    prompt: Enter password
    private: true
  tasks:
  - include_role: {name: user, tasks_from: create}
