- name: "Determine distribution"
  set_fact:
    distribution: "{{ ansible_distribution }}"

- name: "Determine distribution"
  set_fact:
    distribution: "{{ ansible_lsb['id'] }}"
  when: "distribution == 'Debian'"

- name: "Define kernel parameters file"
  set_fact:
    kernel_parameters_file: "/boot/cmdline.txt"
  when: "distribution == 'Raspbian'"

- name: "Check if kernel parameters file exists"
  stat:
    path: "{{ kernel_parameters_file }}"
  register: kernel_parameters_stat

- block:
  - name: "Read kernel parameters file"
    become: true
    command:
      cmd: "cat {{ kernel_parameters_file }}"
    register: kernel_parameters_cat_command

  - name: "Read kernel parameters file"
    set_fact:
      kernel_parameters_content: "{{ kernel_parameters_cat_command.stdout_lines[0] }}"
      old_kernel_parameters_content: "{{ kernel_parameters_cat_command.stdout_lines[0] }}"
    
  - name: "Remove kernel parameters"
    set_fact:
      kernel_parameters_content: '{{ kernel_parameters_content | regex_replace(item.key + "=[^\s]*\s*", "") }}'
    with_items: "{{ kernel_parameters }}"

  - name: "Detect if kernel parameters changed"
    set_fact:
      kernel_parameters_changed: "{{ kernel_parameters_content != old_kernel_parameters_content }}"
  
  - block:
    - name: "Writing kernel parameters"
      become: true
      copy:
        content: "{{ kernel_parameters_content }}"
        dest: "{{ kernel_parameters_file }}"
    
    - name: "Rebooting"
      become: true
      reboot:
    when: kernel_parameters_changed
  when: kernel_parameters_stat.stat.exists


